# Generated by Django 5.1.2 on 2024-10-12 12:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClinicalTrial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="EAP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eap_number", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MedicalCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("abbreviation", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "contactid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_lead", models.BooleanField(default=False)),
                ("first_contact_date", models.DateTimeField(blank=True, null=True)),
                ("initial_consult_date", models.DateTimeField(blank=True, null=True)),
                (
                    "medical_condition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.medicalcondition",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EAPDossier",
            fields=[
                (
                    "eap_dossier_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("eap_enrollment_date", models.DateTimeField()),
                (
                    "eap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.eap"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.patient"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="eap",
            name="patients",
            field=models.ManyToManyField(through="api.EAPDossier", to="api.patient"),
        ),
        migrations.CreateModel(
            name="CTReferall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eligible", models.BooleanField()),
                (
                    "ineligible_reason",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("ct_referral_date", models.DateTimeField()),
                ("ct_outcome", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "ct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.clinicaltrial",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.patient"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="clinicaltrial",
            name="patients",
            field=models.ManyToManyField(through="api.CTReferall", to="api.patient"),
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_date", models.DateTimeField()),
                ("reminder_date", models.DateTimeField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.patient"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Specialist",
            fields=[
                (
                    "contactid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("PHYSICIAN", "Physician"),
                            ("PHARMACISTS", "Pharmacist"),
                        ],
                        max_length=20,
                    ),
                ),
                ("job_title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "medical_license_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.hospital",
                    ),
                ),
                (
                    "specialization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.specialization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="patient",
            name="physician",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.specialist",
            ),
        ),
    ]
